In [2]:
import numpy as np


In [1]:
data1 = [1,2,3,4,5]
data1

[1, 2, 3, 4, 5]

In [2]:
data2 = [1,2,3,4,5]
data2

[1, 2, 3, 4, 5]

In [6]:
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [7]:
arr1.shape
# 넘파이의 배열의 길이를 튜플 형식으로 나타내준다.

(5,)

In [10]:
arr1.dtype
# 넘파이 배열의 값의 자료형을 나타내준다.

dtype('int64')

In [9]:
arr2 = np.array([1,2,3,4,5]) 
arr2
# 1차원 데이터

array([1, 2, 3, 4, 5])

In [11]:
arr3 = np.array(data2)
arr3

array([1, 2, 3, 4, 5])

In [14]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr4
# 2차원 데이터


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
arr4.shape

(4, 3)

In [16]:
array5 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array5.shape
# 3차원 데이터

(2, 2, 2)

# 넘파이 기본 함수

In [17]:
np.arange(10)
# 배열을 생성하는 함수, 지정해준 값-1 까지 배열을 생성해준다.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(3,10)
# 범위를 지정 할 수 있다.
np.arange(0,10,2)
# 범위를 지정해 주고 동시에 배열값의 증감폭도 지정해 줄 수 있다.

array([0, 2, 4, 6, 8])

In [20]:
np.zeros(10)
# 값이 0으로 이루어진 배열을 생성한다.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.ones(9)
# 값이 1로 이루어진 배열을 생성한다.

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

# reshape


In [23]:
ones_array = np.ones((3,4), dtype='int32')
print(ones_array)
print("Data Type is:", ones_array.dtype)
print("Data Shape is:", ones_array.shape)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Data Type is: int32
Data Shape is: (3, 4)


In [24]:
after_reshape = ones_array.reshape(6,2)
print(after_reshape)
print("Data Shape is:", after_reshape.shape)
# 배열의 형태를 변형해줄 수 있다.

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
Data Shape is: (6, 2)


In [25]:
after_reshape = ones_array.reshape(5,3)
# cannot reshape array of size 12 into shape (5,3)
# 이 뜻은 원래 배열의 값(12) 보다 더 크게 배열을 만들 수 없을을 뜻한다.

ValueError: ignored

In [26]:
after_reshape = ones_array.reshape(2,3,2)
print(after_reshape)
print("Data Shape is:", after_reshape.shape)
# 2차원 3x4 배열을 3차원 2x3x2의 형태로 만들어 줄 수 있다.

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]
Data Shape is: (2, 3, 2)


In [27]:
after_reshape2= ones_array.reshape(-1,6)
print("reshape(-1,6)? \n")
print(after_reshape2)
# 배열을 바꿔줄때, 앞에 -1을 넣을 경우 자동으로 뒤의 숫자에 맞춰 리쉐이프를 진행해준다

reshape(-1,6)? 

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]]


# Array 연산
 - Array연산은 기본적으로 크기가 서로 동일해야 진행된다.
 - 이때 같은 위치에 있는 요소들 끼리 연산된다.

In [3]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1


array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr2 = np.array([[10,11,12],[13,14,15]])
arr2



array([[10, 11, 12],
       [13, 14, 15]])

In [5]:
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [6]:
arr1 - arr2

array([[-9, -9, -9],
       [-9, -9, -9]])

In [7]:
arr1 * arr2
# 행렬의 곱셉처럼 진행되는게 아닌, 각 요소별로 곱셈이 진행된다.

array([[10, 22, 36],
       [52, 70, 90]])

In [8]:
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

# Array 브로드 캐스트
 - 브로드캐스트란, 서로 크기가 다른 Array의 연산을 가능캐하는 것 이다.

In [9]:
arr1


array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr3 = np.array([10,11,12])
arr3




array([10, 11, 12])

In [12]:
arr1 + arr3
# 이 결과처럼 arr1에 arr3이 각각 더해진다.

array([[11, 13, 15],
       [14, 16, 18]])

In [13]:
arr1 * arr3

array([[10, 22, 36],
       [40, 55, 72]])

# 그 외 연산

In [14]:
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [15]:
arr1 ** 2
# 요소값에 제곱

array([[ 1,  4,  9],
       [16, 25, 36]])

# Array boolean 인덱싱(마스크)
 - Array의 다차원 인덱싱을 응용하여 boolean 인덱싱을 할 수 있다.
 - 이러한 방법을 마스크라고 이야기한다
 - 마스크처럼 원하는 요소만을 꺼낼 수 있다.

In [16]:
names = np.array(['A','B','C','D','E','F','G','H'])
names



array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'], dtype='<U1')

In [17]:
data = np.random.randn(8,4)
data

#.random.randn 기대값 0  표준편차가 1인 난수를 발생시켜주는 함수다



array([[-0.78574336,  0.48987839,  0.82645617, -0.17152028],
       [-0.3937686 , -0.93822294,  2.14477087,  0.14940101],
       [ 1.43828557,  0.47514969, -0.08924484, -0.96863949],
       [ 0.38315778,  0.52111372,  0.05168264, -0.73003927],
       [ 1.22600484, -0.31477497, -0.70510052, -1.42081814],
       [-0.76256766,  0.61905043, -0.42352021,  1.8825546 ],
       [ 0.72534189, -2.13280186,  0.72306828,  1.18772154],
       [ 1.31611304,  0.98261818,  0.38594941, -0.25431404]])

names 와 data라는 두 array이가 있을때, 각 요소의 행이 연결되었고
names가 A 인 행의 data를 본다고 하면 아래와 같이 해야한다.

In [20]:
# 요소가 A인 항목에 대한 mask 생성
names_A_mask = (names == 'A')
names_A_mask


array([ True, False, False, False, False, False, False, False])

In [21]:
data[names_A_mask,:]

array([[-0.78574336,  0.48987839,  0.82645617, -0.17152028]])

위의 값을 본다면 0행의 값이 A인 것을 알 수 있다.

In [22]:
data[names == 'B',:]
# 요소가 B인 행의 데이터만 꺼내기

array([[-0.3937686 , -0.93822294,  2.14477087,  0.14940101]])

In [23]:
data[(names == 'C') | (names == 'D'),:]

#논리값을 이용해 C 또는 D인 행의 데이터만 꺼내기

array([[ 1.43828557,  0.47514969, -0.08924484, -0.96863949],
       [ 0.38315778,  0.52111372,  0.05168264, -0.73003927]])

data array 자체적으로도 마스크를 만들고 응용이 가능하다.
0번째 열이 0보다 작은 행을 구한다면 어떻게 해야할까?

In [24]:
data[:,0] < 0
#먼저 data array에서 0번째 열이 0보다 작은 요소의 값은 다음과 같다.

array([ True,  True, False, False, False,  True, False, False])

In [25]:
data[data[:,0]<0,:]
#위에서 만든 마스크를 이용해 0번째 열의 값이 0보다 작은 행을 구한다. 

array([[-0.78574336,  0.48987839,  0.82645617, -0.17152028],
       [-0.3937686 , -0.93822294,  2.14477087,  0.14940101],
       [-0.76256766,  0.61905043, -0.42352021,  1.8825546 ]])

In [26]:
data[data[:,0]<0,2:4]
#이걸 응용하면 특정위치에 값을 대입할 수 있다.
#위의 코드는 0번째 열의 값이 0보다 작은 행의 2.3번째 열값이다.

array([[ 0.82645617, -0.17152028],
       [ 2.14477087,  0.14940101],
       [-0.42352021,  1.8825546 ]])

In [27]:
data[data[:,0]<0,2:4] = 0
data

#이렇게 구한 열값에 0을 대입하면 아래와 같은 결과를 얻을 수 있다.


array([[-0.78574336,  0.48987839,  0.        ,  0.        ],
       [-0.3937686 , -0.93822294,  0.        ,  0.        ],
       [ 1.43828557,  0.47514969, -0.08924484, -0.96863949],
       [ 0.38315778,  0.52111372,  0.05168264, -0.73003927],
       [ 1.22600484, -0.31477497, -0.70510052, -1.42081814],
       [-0.76256766,  0.61905043,  0.        ,  0.        ],
       [ 0.72534189, -2.13280186,  0.72306828,  1.18772154],
       [ 1.31611304,  0.98261818,  0.38594941, -0.25431404]])